### ISSUE TITLE
Replace `from typing import Tuple` with PEP 585 syntax

### ISSUE THREAD

**Issue by StrohMatanya** [YoniChechik/parametric#34]
PEP 585 introduced a new syntax for type hinting generic types, including tuples. 
This syntax provides more concise and expressive type annotations compared to the traditional from typing import Tuple approach.   

**Advantages of PEP 585:**
- Improved readability: The syntax is more intuitive and easier to understand.
- Consistency: Aligns with the typing syntax for other generic types.
- Potential performance benefits: Some reports suggest potential performance improvements (most likely will be negligible in most cases, but still I need 3 good reasons :-) ).

**Disadvantages of from typing import Tuple:**
- Verbosity: Requires additional import statements.
- Less intuitive: Can be less readable compared to the PEP 585 syntax.

From [PEP585: Implementation](https://peps.python.org/pep-0585/#implementation):
> Importing those from typing is deprecated. Due to [PEP 563](https://peps.python.org/pep-0563/) and the intention to minimize the runtime impact of typing, this deprecation will not generate DeprecationWarnings. Instead, type checkers may warn about such deprecated usage when the target version of the checked program is signalled to be Python 3.9 or newer. It’s recommended to allow for those warnings to be silenced on a project-wide basis.

> The deprecated functionality may eventually be removed from the typing module. Removal will occur no sooner than Python 3.9’s end of life, scheduled for October 2025.

I saw that you are using both `Tuple` and `tuple` for some places in the code, but since PEP585 introduced in Python3.9 and there is a requirements for Python3.10 and above, so I'm wondering is there a specific reason for not adopting the PEP 585 syntax for tuple type hinting in this codebase?

See [PEP585](https://peps.python.org/pep-0585/)

**Comment by YoniChechik** [comment]
We need to be able to support users that wants to use the old format, which isn't deprecated... Your thoughts?

**Comment by YoniChechik** [comment]
@StrohMatanya ?

**Comment by StrohMatanya** [comment]
Sorry for the delayed response.

While I'm in favor of using  `tuple`, you are right here,  it's crucial to consider the needs of our users. Given the number of users relying on the old method, maintaining compatibility seems essential.
What are your thought's about adding a msg saying that it will be deprecated in the future?

**Comment by YoniChechik** [comment]
I'd like to support it as long as python itself supports it. Doesnt seems that hard currently.
